/*
 * This class forms part of the Dynamic Proxies in Java Course by
 * Dr Heinz Max Kabutz from JavaSpecialists.eu and may not be distributed
 * without written consent.
 *
 * Copyright 2020, Dr Heinz Max Kabutz, All rights reserved.
 */

package dynamicproxies.ch2.exercise22;

import dynamicproxies.util.measurement.*;

import java.sql.*;

// TODO: This class must implement PreparedStatement
// TODO: Use the TimeMeasuringHandler to record the time taken for all
// TODO: methods with 'execute' in the name, and also
// TODO: for 'setObject(int,Object)', 'addBatch' and 'close'
public class PreparedStatementProxy {
  public PreparedStatementProxy(PreparedStatement preparedStatement,
                                TimeMeasuringHandler handler) {
  }

  public long executeLargeUpdate(String sql,
                                 int autoGeneratedKeys) throws SQLException {
    /*
      e.g.
    try (var measurer = handler.start("java.sql.PreparedStatement",
        "executeLargeUpdate", sql, autoGeneratedKeys)) {
      return preparedStatement.executeLargeUpdate(sql,
          autoGeneratedKeys);
    }
     */
    throw new UnsupportedOperationException("TODO");
  }
}